name: Bug report
description: Report a reproducible problem.
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened
      description: Describe the actual behavior you observed.
      placeholder: The app did X when I did Y.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected instead.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, numbered set of steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: input
    id: browser_os
    attributes:
      label: Browser + OS
      description: Include browser version and operating system.
      placeholder: Chrome 123 on Windows 11
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Drag/drop an image or paste a link.

  - type: textarea
    id: logs
    attributes:
      label: Logs (console output)
      description: Paste relevant browser console output.
      render: shell
