name: Feature request
description: Suggest an improvement for the project.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem are you trying to solve?
      placeholder: It is hard to...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: Describe the change you want.
      placeholder: We should add...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe other approaches you considered.

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: List testable criteria for completion.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
